# Generated by Django 4.2.2 on 2023-08-25 07:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
